language: python
python:
#  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
#  - "pypy"
  - "pypy3"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test tests --doctest-modules --pep8 permuta -v --cov permuta --cov-report term-missing
after_success:
  - coveralls
