language: python
python:
  # - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
install:
  - pip install -e .
before_script:
  - pip install -r test_requirements.txt
script:
  - pytest --cov=permuta --cov-report=term-missing
after_success:
  - coveralls
