language: python
python:
#  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
#  - "pypy"
  - "pypy3"
install:
  - pip install -e .
before_script:
  - pip install -r test_requirements.txt
script:
  - pytest tests --doctest-ignore-import-errors --pep8 -v --cov=permuta --cov-report=term-missing
after_success:
  - coveralls
