language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=black

    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39
    - python: pypy3.5-6.0
      env: TOXENV=pypy35
    - python: pypy3
      env: TOXENV=pypy36


install:
  - pip install tox

script:
  - tox

deploy:
  provider: pypi
  user: henningu
  password:
    secure: bhjQyIm/xGmUBq7bYpYYoXyt21tJQM9XU/eymPbnEXJhX0Z+KY58JmmorTG7PslJoARsi4ZXUA3N4Oqu/n4lReo1FQ7dahbdKUNYWuFx7ZZRvJLDW/tFd1gKO07bpTMJHxXMoyIhbmSllXxgRDJ/TBtI+uvYBMcR02CiZAFW8uN+3Vg0k+c1Njx0RR7h/1Dzw3iwupBzykT/bZW4zMs5XuqFjGaqCdymcWEEmjo+b0yZQ05i0dFkonzaBpM9S1HdDG6DvD4O7KKJdPTCcpFNd4HqN3giXicMA0faH8zOqeKhJ5mON90YAuNppkGUOt49FupQAeCAl3gSAKTrQnam4GxipCGuzFOjysHvv0MQcmGQ1n2bsD249r2qSo0AiabFtyJPHoZdBrs/1cqMks7suhAjydrAnkR+xz/a//5HRV1q73SAEtOI7CFCkoTFuU6yCG8US0EmZUDDe+kcPGb0Qwpol8AO+8B+Ih2OaYfyCGTBZ6Wrx64SjWE1KDjC4R8HJmzJCPsgL99Ab8KA66xmQqiZROy6qnwtyMV4oWz/BOsvWJg577ItX6ItmEC8tOGNm/yW1QTlgUZkk/0sOd0usAbdvp4a+rZKMYd9MKin76MnktQ56tI5Vfnelk+bcRe6Cz1tIrq82NxhSl44OqK2yCJ3ksSdBBkWfxa7jp7yAkQ=
  skip_existing: true
  on:
    branch: master
