from itertools import islice
from typing import ClassVar, Dict, FrozenSet, Iterable, Iterator, Tuple

from permuta.patterns.perm import Perm


class PolyPerm:
    """A static container of methods to check if a perm set has a polynomial growth."""

    PERM_TYPE_0: ClassVar[int] = 0  # W++
    PERM_TYPE_1: ClassVar[int] = 1  # W+-
    PERM_TYPE_2: ClassVar[int] = 2  # W-+
    PERM_TYPE_3: ClassVar[int] = 3  # W--
    PERM_TYPE_4: ClassVar[int] = 4  # Winv++
    PERM_TYPE_5: ClassVar[int] = 5  # Winv+-
    PERM_TYPE_6: ClassVar[int] = 6  # Winv-+
    PERM_TYPE_7: ClassVar[int] = 7  # Winv--
    PERM_TYPE_8: ClassVar[int] = 8  # L2
    PERM_TYPE_9: ClassVar[int] = 9  # L2inv
    _CACHE: ClassVar[Dict[Perm, FrozenSet]] = {}

    @staticmethod
    def _types(perm: Perm) -> FrozenSet[int]:
        interset = PolyPerm._CACHE.get(perm)
        if interset is None:
            interset = frozenset(PolyPerm._find_type(perm))
            PolyPerm._CACHE[perm] = interset
        return interset

    @staticmethod
    def _type_0_3(slice1: Tuple[int, ...], slice2: Tuple[int, ...]) -> Iterator[int]:
        if PolyPerm._is_incr(slice1):
            if PolyPerm._is_incr(slice2):
                yield PolyPerm.PERM_TYPE_0
            if PolyPerm._is_decr(slice2):
                yield PolyPerm.PERM_TYPE_1

        if PolyPerm._is_decr(slice1):
            if PolyPerm._is_incr(slice2):
                yield PolyPerm.PERM_TYPE_2
            if PolyPerm._is_decr(slice2):
                yield PolyPerm.PERM_TYPE_3

    @staticmethod
    def _type_4_7(slice1: Tuple[int, ...], slice2: Tuple[int, ...]) -> Iterator[int]:
        if PolyPerm._is_incr(slice1):
            if PolyPerm._is_incr(slice2):
                yield PolyPerm.PERM_TYPE_4
            if PolyPerm._is_decr(slice2):
                yield PolyPerm.PERM_TYPE_5

        if PolyPerm._is_decr(slice1):
            if PolyPerm._is_incr(slice2):
                yield PolyPerm.PERM_TYPE_6
            if PolyPerm._is_decr(slice2):
                yield PolyPerm.PERM_TYPE_7

    @staticmethod
    def _find_type(perm: Perm) -> Iterable[int]:
        flipperm = perm.inverse()
        for i in range(len(perm) + 1):
            yield from PolyPerm._type_0_3(perm[0:i], perm[i:])
            yield from PolyPerm._type_4_7(flipperm[0:i], flipperm[i:])
        if PolyPerm._of_type_8(perm):
            yield PolyPerm.PERM_TYPE_8
        if PolyPerm._of_type_8(perm.reverse()):
            yield PolyPerm.PERM_TYPE_9

    @staticmethod
    def _is_decr(perm_slice: Tuple[int, ...]) -> bool:
        return all(
            prev > curr for prev, curr in zip(perm_slice, islice(perm_slice, 1, None))
        )

    @staticmethod
    def _is_incr(perm_slice: Tuple[int, ...]) -> bool:
        return all(
            prev < curr for prev, curr in zip(perm_slice, islice(perm_slice, 1, None))
        )

    @staticmethod
    def _of_type_8(perm_slice: Tuple[int, ...]) -> bool:
        n = len(perm_slice)
        if n < 2:
            return True
        if perm_slice[-1] == n - 1:
            return PolyPerm._of_type_8(perm_slice[0 : n - 1])
        if perm_slice[-1] == n - 2 and perm_slice[-2] == n - 1:
            return PolyPerm._of_type_8(perm_slice[0 : n - 2])
        return False

    @staticmethod
    def is_polynomial(basis: Iterable[Perm]) -> bool:
        """True iff the perm set generated by basis has polynomial growth."""
        return (
            len({pol_type for perm in basis for pol_type in PolyPerm._types(perm)})
            == 10
        )

    @staticmethod
    def is_non_polynomial(basis: Iterable[Perm]) -> bool:
        """False iff the perm set generated by basis has polynomial growth."""
        return not PolyPerm.is_polynomial(basis)
